### ISSUE TITLE
Allow mapping for dynamic labels

### ISSUE THREAD

**Issue by kpiwko** [rsvoboda/gh-exporter#4]
As an user of *gh-exporter*, I would like to be able to use it for GitHub projects with different label system, so that I can gather metrics for different repository.

Desired mapping:
* Issue kinds (bug, feature request, task...)
* Severity/Priority - might require multiple labels and and/or statement
* Status labels - blocked, resolved, pending verification, ...
* Sizing labels - M, L, XL, XXL, ...
* Compenent and other drilldown labels

**Comment by rsvoboda** [comment]
What about combinations of these mappings? Any limitations or any combination is possible? 

Be aware of GitHub Search API limits - https://github.com/rsvoboda/gh-exporter#calls-to-github-search-api

**Comment by rsvoboda** [comment]
I assume we are talking about issues and custom searches/metrics on top of it.

I plan to introduce CUSTOM GHDetailsLevel

GH searches would be composed this way:
`https://api.github.com/search/issues?per_page=1&q=repo:$REPO+is:issue+is:open+$QUERY`
`https://api.github.com/search/issues?per_page=1&q=repo:$REPO+is:issue+is:closed+$QUERY`

$REPO would come from `gh.repos` configuration
$QUERY would come from `gh.open.issues` / `gh.closed.issues` configuration

Example of configuration via application.properties:
```properties
gh.details.level=CUSTOM
gh.repos=quarkusio/quarkus, quarkusio/quarkus-quickstarts
gh.open.issues=\
  label:kind/extension-proposal,\
  label:kind/enhancement,\
  label:area/persistence,\
  label:area/persistence+label:kind/enhancement
gh.closed.issues=${gh.open.issues}
```

@kpiwko Does this meet your expectations?

**Comment by rsvoboda** [comment]
Example of deploy - https://github.com/rsvoboda/gh-jira-metrics/commit/f2a9d6a6f0ff0961a971440b824bd14a8187335c
